inherit_from: ../.rubocop.yml

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false
  
Metrics/ModuleLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false
